### ISSUE TITLE
SpecificValueMissingValuePolicy - decision: generics vs 'variant'

### ISSUE THREAD

**Issue by hcorg** [bartoszkp/TDDEvaluation#14]
to be consistent with Datum<T>, SpecificValueMissingValuePolicy should also be a <T> generic...

But that is just a paint in the... (it's even worse than Datum<T> problem, as it is a problem with generic subclass of concrete type... damn,,,) Yet it's the only consistent way of doing things now...

Easy solution - use String or some other "general purpose" type as "Value" in SpecificValueMissingValuePolicy, but this is a little bit ugly

I need help to decide, what should we do :)

**Comment by bartoszkp** [comment]
We went with `MissingValuePolicy<T>`.
