### ISSUE TITLE
Add test cases for when `to` is before `from`

### ISSUE THREAD

**Issue by bartoszkp** [bartoszkp/TDDEvaluation#41]
Invalid timestamps in `GetData` are:
 - `from` not properly aligned with granularity (already handled - throws)
 - `to` not properly aligned with granularity (already handled - ignored)
 - `from` after `to` (unspecified)

For the last case possible solutions are:
 - throw
 - return empty result

Invalid timestamps in `SetData` are:
 - data timestamps not properly aligned with granularity (already handled - throws)
 - data timestamps not sorted (unspecified)

For the last case possible solutions are:
 - throw
 - ignore order (if timestamps are correct, they can be stored correctly anyway)

**Comment by hcorg** [comment]
`SetData` does not have `to` and `from` in it's iface, there are just samples passed to it. Question remains: what to do, if samples are given not in rising timestamps order

**Comment by bartoszkp** [comment]
Right - I've fixed the description. Seems only `GetData` needs to be defined - `SetData` should run fine even with incorrect order (still, probably we need a test for that)
