### ISSUE TITLE
SignalsRepository -> GetAllWithPathPrefix doesn't work correctly

### ISSUE THREAD

**Issue by pw94** [bartoszkp/TDDEvaluation#5]
When there are signals with paths:

- twoLevels/topLevelSignal

- twoLevels2/topLevelSignal

I would like to get all signals with path prefix 'twoLevels'. I will get both signals listed above, not only first one.

**Comment by hcorg** [comment]
fixed in 1a90f1c5ec74834e6157fde3b1dfbbf62467f083
