### ISSUE TITLE
Provide a function or determine a convention for deleting signal's data

### ISSUE THREAD

**Issue by bartoszkp** [bartoszkp/TDDEvaluation#9]
Either add a function, which will allow deleting signal's value or determine that `Quality.None` is a universal indicator for lack of value.

**Comment by hcorg** [comment]
@bartoszkp: did #32 resolve this issue also?

**Comment by bartoszkp** [comment]
@hcorg No. When signal is being deleted it naturally follows that everything associated with it vanishes. This has nothing to do with the following scenario: 1) Add a signal 2) Add some data 3) Delete some data (signal still exists).

**Comment by bartoszkp** [comment]
`Quality.None` is enough to indicate lack of data.
